### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DivyaPathrabe**

### CODE REVIEW

**Review by MaheshLikhar — COMMENTED** [review]
ky masta likhi hai bhai

**Comment by DivyaPathrabe** [comment]
tere liye baat hai

**Comment by MaheshLikhar** [comment]
hao

**Comment by DivyaPathrabe** [comment]
chalo aa gaya use krte

**Comment by DivyaPathrabe** [comment]
whatsapp ban bhi hua to best hai

**Pull request merged**
